### ISSUE TITLE
Clipboard Access

### ISSUE THREAD

**Issue by 89jd** [Mesteery/AndroidVSCode#1]
Hi,

I can't paste from android clipboard to browser. In chrome it asks for permission, done some googling, but can't find exact way of sharing API from native to WebView. Maybe needs JavaScript interface

**Comment by Mesteery** [comment]
what is not working

**Comment by 89jd** [comment]
So, copy something to clipboard outside of your app -> paste in app -> nothing happens

**Comment by Mesteery** [comment]
Can i have a video record?
